name: List GCS Buckets

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  list-buckets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/390395656114/locations/global/workloadIdentityPools/github/providers/ghactions-gcp-example
        service_account: ghactions-gcp@ghactions-46891.iam.gserviceaccount.com

    - name: List GCS Buckets
      run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud storage buckets list